apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.project }}-config
  labels:
    app.kubernetes.io/name: {{ .Values.project }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  openclaw.json: |
    {{- .Files.Get "config/openclaw.json" | nindent 4 }}
  AGENTS.md: |
    {{- .Files.Get "config/AGENTS.md" | nindent 4 }}
